name: ethos
version: '${version}'
main: ru.nyansus.mc.ethos.Ethos
api-version: '1.21'
author: Nyansus
softdepend:
  - PlaceholderAPI

commands:
  karma:
    description: View or manage karma
    usage: /karma [player|reset|effects|set <player> <value>]
    permission: ethos.karma.view
  etitle:
    description: Manage your titles
    usage: /etitle [id|all [page]|page <page>|reset|info <id>|give <player> <id>]
    permission: ethos.title.use
    aliases: [dt, et]
  ethos:
    description: Admin commands
    usage: /ethos reload
    permission: ethos.admin

permissions:
  ethos.karma.view:
    description: View your own karma
    default: true
  ethos.karma.view.others:
    description: View other players' karma
    default: true
  ethos.karma.admin:
    description: Set karma for other players
    default: op
  ethos.admin:
    description: Plugin admin commands (reload)
    default: op
  ethos.title.use:
    description: View and select titles
    default: true
  ethos.title.admin:
    description: Give titles to other players
    default: op
